/** @deprecated Importe de `financeCalculator.ts`. Reexportações de compatibilidade. */
export {
  calculateSettlementDate,
  calculateSettlementDateFromFlow,
  calculateParcelDueDate,
  calculateNetValue,
  resolveMaquininhaFee as calculateMaquininhaFee,
  resolveMaquininhaPaymentMethod,
  settlementPlanForMaquininhaPlan,
  buildMaquininhaSettlementContext,
  isMaquininhaAnticipatedPlan,
  maquininhaSettlementReceiptType,
  effectiveInstallmentCountForSettlement,
  startOfDay,
  formatDateOnly,
  parseDateInput,
  isSameCalendarDay,
  nextBusinessDayAfter,
  flowToPaymentMethod,
  type PaymentMethodFlow,
  type SettlementPlan,
  type SettlementReceiptType,
} from './financeCalculator';
